services:
  redis:
    image: redis:7-alpine
    container_name: fluxx-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  mysql:
    image: mysql:8.4
    container_name: fluxx-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_: root
      MYSQL_DATABASE: fluxx
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1

    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  redis_data:
  mysql_data:
